# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structs/Genetics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import ProductKey_pb2 as base_dot_ProductKey__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='structs/Genetics.proto',
  package='opencannabis.structs',
  syntax='proto3',
  serialized_pb=_b('\n\x16structs/Genetics.proto\x12\x14opencannabis.structs\x1a\x15\x62\x61se/ProductKey.proto\"r\n\x08Genetics\x12\x31\n\x04male\x18\x01 \x01(\x0b\x32#.opencannabis.base.ProductReference\x12\x33\n\x06\x66\x65male\x18\x02 \x01(\x0b\x32#.opencannabis.base.ProductReferenceBB\n%io.opencannabis.schema.product.structB\x0fGeneticsStructsH\x01P\x01\xa2\x02\x03OCSb\x06proto3')
  ,
  dependencies=[base_dot_ProductKey__pb2.DESCRIPTOR,])




_GENETICS = _descriptor.Descriptor(
  name='Genetics',
  full_name='opencannabis.structs.Genetics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='male', full_name='opencannabis.structs.Genetics.male', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='female', full_name='opencannabis.structs.Genetics.female', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=185,
)

_GENETICS.fields_by_name['male'].message_type = base_dot_ProductKey__pb2._PRODUCTREFERENCE
_GENETICS.fields_by_name['female'].message_type = base_dot_ProductKey__pb2._PRODUCTREFERENCE
DESCRIPTOR.message_types_by_name['Genetics'] = _GENETICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Genetics = _reflection.GeneratedProtocolMessageType('Genetics', (_message.Message,), dict(
  DESCRIPTOR = _GENETICS,
  __module__ = 'structs.Genetics_pb2'
  # @@protoc_insertion_point(class_scope:opencannabis.structs.Genetics)
  ))
_sym_db.RegisterMessage(Genetics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%io.opencannabis.schema.product.structB\017GeneticsStructsH\001P\001\242\002\003OCS'))
# @@protoc_insertion_point(module_scope)
