# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commerce/Item.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import ProductKey_pb2 as base_dot_ProductKey__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='commerce/Item.proto',
  package='commerce',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x63ommerce/Item.proto\x12\x08\x63ommerce\x1a\x15\x62\x61se/ProductKey.proto\"\x8c\x01\n\x0bVariantSpec\x12)\n\x07variant\x18\x01 \x01(\x0e\x32\x18.commerce.ProductVariant\x12)\n\x06weight\x18\x02 \x01(\x0e\x32\x17.commerce.ProductWeightH\x00\x12\x0e\n\x04size\x18\x03 \x01(\tH\x00\x12\x0f\n\x05\x63olor\x18\x04 \x01(\tH\x00\x42\x06\n\x04spec\"y\n\x04Item\x12\x1d\n\x03key\x18\x01 \x01(\x0b\x32\x10.base.ProductKey\x12&\n\x07variant\x18\x02 \x03(\x0b\x32\x15.commerce.VariantSpec\x12\r\n\x05\x63ount\x18\x03 \x01(\r\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x0c\n\x04\x63ost\x18\x05 \x01(\x01*1\n\x0eProductVariant\x12\n\n\x06WEIGHT\x10\x00\x12\t\n\x05\x43OLOR\x10\x01\x12\x08\n\x04SIZE\x10\x02*a\n\rProductWeight\x12\r\n\tNO_WEIGHT\x10\x00\x12\x0c\n\x08HALFGRAM\x10\x01\x12\x08\n\x04GRAM\x10\x02\x12\n\n\x06\x45IGHTH\x10\x03\x12\x0b\n\x07QUARTER\x10\x04\x12\x08\n\x04HALF\x10\x05\x12\x06\n\x02OZ\x10\x06\x42/\n\x1bio.bloombox.schema.commerceB\tOrderItemH\x01P\x00\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[base_dot_ProductKey__pb2.DESCRIPTOR,])

_PRODUCTVARIANT = _descriptor.EnumDescriptor(
  name='ProductVariant',
  full_name='commerce.ProductVariant',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WEIGHT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLOR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIZE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=322,
  serialized_end=371,
)
_sym_db.RegisterEnumDescriptor(_PRODUCTVARIANT)

ProductVariant = enum_type_wrapper.EnumTypeWrapper(_PRODUCTVARIANT)
_PRODUCTWEIGHT = _descriptor.EnumDescriptor(
  name='ProductWeight',
  full_name='commerce.ProductWeight',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_WEIGHT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HALFGRAM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRAM', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EIGHTH', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUARTER', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HALF', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OZ', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=373,
  serialized_end=470,
)
_sym_db.RegisterEnumDescriptor(_PRODUCTWEIGHT)

ProductWeight = enum_type_wrapper.EnumTypeWrapper(_PRODUCTWEIGHT)
WEIGHT = 0
COLOR = 1
SIZE = 2
NO_WEIGHT = 0
HALFGRAM = 1
GRAM = 2
EIGHTH = 3
QUARTER = 4
HALF = 5
OZ = 6



_VARIANTSPEC = _descriptor.Descriptor(
  name='VariantSpec',
  full_name='commerce.VariantSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant', full_name='commerce.VariantSpec.variant', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='commerce.VariantSpec.weight', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='commerce.VariantSpec.size', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='commerce.VariantSpec.color', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='spec', full_name='commerce.VariantSpec.spec',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=57,
  serialized_end=197,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='commerce.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='commerce.Item.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variant', full_name='commerce.Item.variant', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='commerce.Item.count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='commerce.Item.price', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cost', full_name='commerce.Item.cost', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=320,
)

_VARIANTSPEC.fields_by_name['variant'].enum_type = _PRODUCTVARIANT
_VARIANTSPEC.fields_by_name['weight'].enum_type = _PRODUCTWEIGHT
_VARIANTSPEC.oneofs_by_name['spec'].fields.append(
  _VARIANTSPEC.fields_by_name['weight'])
_VARIANTSPEC.fields_by_name['weight'].containing_oneof = _VARIANTSPEC.oneofs_by_name['spec']
_VARIANTSPEC.oneofs_by_name['spec'].fields.append(
  _VARIANTSPEC.fields_by_name['size'])
_VARIANTSPEC.fields_by_name['size'].containing_oneof = _VARIANTSPEC.oneofs_by_name['spec']
_VARIANTSPEC.oneofs_by_name['spec'].fields.append(
  _VARIANTSPEC.fields_by_name['color'])
_VARIANTSPEC.fields_by_name['color'].containing_oneof = _VARIANTSPEC.oneofs_by_name['spec']
_ITEM.fields_by_name['key'].message_type = base_dot_ProductKey__pb2._PRODUCTKEY
_ITEM.fields_by_name['variant'].message_type = _VARIANTSPEC
DESCRIPTOR.message_types_by_name['VariantSpec'] = _VARIANTSPEC
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.enum_types_by_name['ProductVariant'] = _PRODUCTVARIANT
DESCRIPTOR.enum_types_by_name['ProductWeight'] = _PRODUCTWEIGHT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VariantSpec = _reflection.GeneratedProtocolMessageType('VariantSpec', (_message.Message,), dict(
  DESCRIPTOR = _VARIANTSPEC,
  __module__ = 'commerce.Item_pb2'
  # @@protoc_insertion_point(class_scope:commerce.VariantSpec)
  ))
_sym_db.RegisterMessage(VariantSpec)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'commerce.Item_pb2'
  # @@protoc_insertion_point(class_scope:commerce.Item)
  ))
_sym_db.RegisterMessage(Item)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.bloombox.schema.commerceB\tOrderItemH\001P\000\370\001\001'))
# @@protoc_insertion_point(module_scope)
