# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytics/context/Browser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bq_field_pb2 as bq__field__pb2
from structs import Version_pb2 as structs_dot_Version__pb2
from analytics.context import OS_pb2 as analytics_dot_context_dot_OS__pb2
from analytics.context import Library_pb2 as analytics_dot_context_dot_Library__pb2
from analytics.context import Application_pb2 as analytics_dot_context_dot_Application__pb2
from analytics.context import NativeDevice_pb2 as analytics_dot_context_dot_NativeDevice__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='analytics/context/Browser.proto',
  package='analytics.context',
  syntax='proto3',
  serialized_pb=_b('\n\x1f\x61nalytics/context/Browser.proto\x12\x11\x61nalytics.context\x1a\x0e\x62q_field.proto\x1a\x15structs/Version.proto\x1a\x1a\x61nalytics/context/OS.proto\x1a\x1f\x61nalytics/context/Library.proto\x1a#analytics/context/Application.proto\x1a$analytics/context/NativeDevice.proto\"\xa8\x04\n\x14\x42rowserDeviceContext\x12_\n\x0c\x62rowser_type\x18\x01 \x01(\x0e\x32\x1e.analytics.context.BrowserTypeB)\xf0?\x01\x8a@#Specifies the general browser type.\x12G\n\x07version\x18\x02 \x01(\x0b\x32\x14.structs.VersionSpecB \x8a@\x1dVersion info for the browser.\x12\x41\n\x08language\x18\x03 \x01(\tB/\x8a@,Active language, as reported by the browser.\x12M\n\nuser_agent\x18\x04 \x01(\tB9\x8a@6Raw user-agent string sent or embedded by the browser.\x12\x46\n\x0btouchpoints\x18\x05 \x01(\rB1\x8a@.Maximum touch points for a particular browser.\x12N\n\x14hardware_concurrency\x18\x06 \x01(\rB0\x8a@-Hardware concurrency reported by the browser.\x12<\n\x0b\x63olor_depth\x18\x07 \x01(\rB\'\x8a@$Color depth reported by the browser.*b\n\x0b\x42rowserType\x12\x13\n\x0f\x42ROWSER_UNKNOWN\x10\x00\x12\n\n\x06\x43HROME\x10\x01\x12\n\n\x06SAFARI\x10\x02\x12\x0b\n\x07\x46IREFOX\x10\x03\x12\t\n\x05OPERA\x10\x04\x12\x0e\n\nIE_OR_EDGE\x10\x05\x42=\n$io.bloombox.schema.telemetry.contextB\x0e\x42rowserContextH\x01P\x00\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[bq__field__pb2.DESCRIPTOR,structs_dot_Version__pb2.DESCRIPTOR,analytics_dot_context_dot_OS__pb2.DESCRIPTOR,analytics_dot_context_dot_Library__pb2.DESCRIPTOR,analytics_dot_context_dot_Application__pb2.DESCRIPTOR,analytics_dot_context_dot_NativeDevice__pb2.DESCRIPTOR,])

_BROWSERTYPE = _descriptor.EnumDescriptor(
  name='BrowserType',
  full_name='analytics.context.BrowserType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BROWSER_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHROME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAFARI', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIREFOX', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPERA', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IE_OR_EDGE', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=784,
  serialized_end=882,
)
_sym_db.RegisterEnumDescriptor(_BROWSERTYPE)

BrowserType = enum_type_wrapper.EnumTypeWrapper(_BROWSERTYPE)
BROWSER_UNKNOWN = 0
CHROME = 1
SAFARI = 2
FIREFOX = 3
OPERA = 4
IE_OR_EDGE = 5



_BROWSERDEVICECONTEXT = _descriptor.Descriptor(
  name='BrowserDeviceContext',
  full_name='analytics.context.BrowserDeviceContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='browser_type', full_name='analytics.context.BrowserDeviceContext.browser_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@#Specifies the general browser type.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='analytics.context.BrowserDeviceContext.version', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\035Version info for the browser.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='analytics.context.BrowserDeviceContext.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@,Active language, as reported by the browser.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_agent', full_name='analytics.context.BrowserDeviceContext.user_agent', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@6Raw user-agent string sent or embedded by the browser.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='touchpoints', full_name='analytics.context.BrowserDeviceContext.touchpoints', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@.Maximum touch points for a particular browser.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hardware_concurrency', full_name='analytics.context.BrowserDeviceContext.hardware_concurrency', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@-Hardware concurrency reported by the browser.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color_depth', full_name='analytics.context.BrowserDeviceContext.color_depth', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@$Color depth reported by the browser.')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=782,
)

_BROWSERDEVICECONTEXT.fields_by_name['browser_type'].enum_type = _BROWSERTYPE
_BROWSERDEVICECONTEXT.fields_by_name['version'].message_type = structs_dot_Version__pb2._VERSIONSPEC
DESCRIPTOR.message_types_by_name['BrowserDeviceContext'] = _BROWSERDEVICECONTEXT
DESCRIPTOR.enum_types_by_name['BrowserType'] = _BROWSERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BrowserDeviceContext = _reflection.GeneratedProtocolMessageType('BrowserDeviceContext', (_message.Message,), dict(
  DESCRIPTOR = _BROWSERDEVICECONTEXT,
  __module__ = 'analytics.context.Browser_pb2'
  # @@protoc_insertion_point(class_scope:analytics.context.BrowserDeviceContext)
  ))
_sym_db.RegisterMessage(BrowserDeviceContext)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$io.bloombox.schema.telemetry.contextB\016BrowserContextH\001P\000\370\001\001'))
_BROWSERDEVICECONTEXT.fields_by_name['browser_type'].has_options = True
_BROWSERDEVICECONTEXT.fields_by_name['browser_type']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@#Specifies the general browser type.'))
_BROWSERDEVICECONTEXT.fields_by_name['version'].has_options = True
_BROWSERDEVICECONTEXT.fields_by_name['version']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\035Version info for the browser.'))
_BROWSERDEVICECONTEXT.fields_by_name['language'].has_options = True
_BROWSERDEVICECONTEXT.fields_by_name['language']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@,Active language, as reported by the browser.'))
_BROWSERDEVICECONTEXT.fields_by_name['user_agent'].has_options = True
_BROWSERDEVICECONTEXT.fields_by_name['user_agent']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@6Raw user-agent string sent or embedded by the browser.'))
_BROWSERDEVICECONTEXT.fields_by_name['touchpoints'].has_options = True
_BROWSERDEVICECONTEXT.fields_by_name['touchpoints']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@.Maximum touch points for a particular browser.'))
_BROWSERDEVICECONTEXT.fields_by_name['hardware_concurrency'].has_options = True
_BROWSERDEVICECONTEXT.fields_by_name['hardware_concurrency']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@-Hardware concurrency reported by the browser.'))
_BROWSERDEVICECONTEXT.fields_by_name['color_depth'].has_options = True
_BROWSERDEVICECONTEXT.fields_by_name['color_depth']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@$Color depth reported by the browser.'))
# @@protoc_insertion_point(module_scope)
