# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/ID.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bq_field_pb2 as bq__field__pb2
from temporal import Date_pb2 as temporal_dot_Date__pb2
from identity.ids import USDL_pb2 as identity_dot_ids_dot_USDL__pb2
from identity.ids import Passport_pb2 as identity_dot_ids_dot_Passport__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity/ID.proto',
  package='identity',
  syntax='proto3',
  serialized_pb=_b('\n\x11identity/ID.proto\x12\x08identity\x1a\x0e\x62q_field.proto\x1a\x13temporal/Date.proto\x1a\x17identity/ids/USDL.proto\x1a\x1bidentity/ids/Passport.proto\"\xbf\x03\n\x02ID\x12?\n\x04type\x18\x01 \x01(\x0e\x32\x10.identity.IDTypeB\x1f\x8a@\x1cType of ID we\'re specifying.\x12\x46\n\x02id\x18\x02 \x01(\tB:\x8a@7ID number or string identifying this identity document.\x12J\n\x0b\x65xpire_date\x18\x03 \x01(\x0b\x32\x0e.temporal.DateB%\x8a@\"Expiration date for this document.\x12J\n\nbirth_date\x18\x04 \x01(\x0b\x32\x0e.temporal.DateB&\x8a@#Birth date listed on this document.\x12I\n\x07license\x18\x14 \x01(\x0b\x32\x12.identity.ids.USDLB\"\x8a@\x1fUnited States Driver\'s License.H\x00\x12\x41\n\x08passport\x18\x15 \x01(\x0b\x32\x16.identity.ids.PassportB\x15\x8a@\x12National passport.H\x00\x42\n\n\x08\x64ocument* \n\x06IDType\x12\x08\n\x04USDL\x10\x00\x12\x0c\n\x08PASSPORT\x10\x01\x42!\n\x1bio.bloombox.schema.identityH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[bq__field__pb2.DESCRIPTOR,temporal_dot_Date__pb2.DESCRIPTOR,identity_dot_ids_dot_USDL__pb2.DESCRIPTOR,identity_dot_ids_dot_Passport__pb2.DESCRIPTOR,])

_IDTYPE = _descriptor.EnumDescriptor(
  name='IDType',
  full_name='identity.IDType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USDL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PASSPORT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=572,
  serialized_end=604,
)
_sym_db.RegisterEnumDescriptor(_IDTYPE)

IDType = enum_type_wrapper.EnumTypeWrapper(_IDTYPE)
USDL = 0
PASSPORT = 1



_ID = _descriptor.Descriptor(
  name='ID',
  full_name='identity.ID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='identity.ID.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\034Type of ID we\'re specifying.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='identity.ID.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@7ID number or string identifying this identity document.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expire_date', full_name='identity.ID.expire_date', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\"Expiration date for this document.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birth_date', full_name='identity.ID.birth_date', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@#Birth date listed on this document.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='license', full_name='identity.ID.license', index=4,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\037United States Driver\'s License.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passport', full_name='identity.ID.passport', index=5,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\022National passport.')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='document', full_name='identity.ID.document',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=123,
  serialized_end=570,
)

_ID.fields_by_name['type'].enum_type = _IDTYPE
_ID.fields_by_name['expire_date'].message_type = temporal_dot_Date__pb2._DATE
_ID.fields_by_name['birth_date'].message_type = temporal_dot_Date__pb2._DATE
_ID.fields_by_name['license'].message_type = identity_dot_ids_dot_USDL__pb2._USDL
_ID.fields_by_name['passport'].message_type = identity_dot_ids_dot_Passport__pb2._PASSPORT
_ID.oneofs_by_name['document'].fields.append(
  _ID.fields_by_name['license'])
_ID.fields_by_name['license'].containing_oneof = _ID.oneofs_by_name['document']
_ID.oneofs_by_name['document'].fields.append(
  _ID.fields_by_name['passport'])
_ID.fields_by_name['passport'].containing_oneof = _ID.oneofs_by_name['document']
DESCRIPTOR.message_types_by_name['ID'] = _ID
DESCRIPTOR.enum_types_by_name['IDType'] = _IDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ID = _reflection.GeneratedProtocolMessageType('ID', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'identity.ID_pb2'
  # @@protoc_insertion_point(class_scope:identity.ID)
  ))
_sym_db.RegisterMessage(ID)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.bloombox.schema.identityH\001P\001'))
_ID.fields_by_name['type'].has_options = True
_ID.fields_by_name['type']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\034Type of ID we\'re specifying.'))
_ID.fields_by_name['id'].has_options = True
_ID.fields_by_name['id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@7ID number or string identifying this identity document.'))
_ID.fields_by_name['expire_date'].has_options = True
_ID.fields_by_name['expire_date']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\"Expiration date for this document.'))
_ID.fields_by_name['birth_date'].has_options = True
_ID.fields_by_name['birth_date']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@#Birth date listed on this document.'))
_ID.fields_by_name['license'].has_options = True
_ID.fields_by_name['license']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\037United States Driver\'s License.'))
_ID.fields_by_name['passport'].has_options = True
_ID.fields_by_name['passport']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\022National passport.'))
# @@protoc_insertion_point(module_scope)
