# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry/v1beta2/commerce/SectionEvents_Beta2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from analytics import Context_pb2 as analytics_dot_Context__pb2
from analytics.commerce import SectionAnalytics_pb2 as analytics_dot_commerce_dot_SectionAnalytics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='telemetry/v1beta2/commerce/SectionEvents_Beta2.proto',
  package='services.telemetry.v1beta2',
  syntax='proto3',
  serialized_pb=_b('\n4telemetry/v1beta2/commerce/SectionEvents_Beta2.proto\x12\x1aservices.telemetry.v1beta2\x1a\x17\x61nalytics/Context.proto\x1a)analytics/commerce/SectionAnalytics.proto\"k\n\x11SectionImpression\x12#\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x12.analytics.Context\x12\x31\n\nimpression\x18\x02 \x01(\x0b\x32\x1d.analytics.section.Impression\"Y\n\x0bSectionView\x12#\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x12.analytics.Context\x12%\n\x04view\x18\x02 \x01(\x0b\x32\x17.analytics.section.View\"_\n\rSectionAction\x12#\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x12.analytics.Context\x12)\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x19.analytics.section.ActionBG\n-io.bloombox.schema.services.telemetry.v1beta2H\x01P\x01\xaa\x02\x11Telemetry.v1beta2b\x06proto3')
  ,
  dependencies=[analytics_dot_Context__pb2.DESCRIPTOR,analytics_dot_commerce_dot_SectionAnalytics__pb2.DESCRIPTOR,])




_SECTIONIMPRESSION = _descriptor.Descriptor(
  name='SectionImpression',
  full_name='services.telemetry.v1beta2.SectionImpression',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='services.telemetry.v1beta2.SectionImpression.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='impression', full_name='services.telemetry.v1beta2.SectionImpression.impression', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=259,
)


_SECTIONVIEW = _descriptor.Descriptor(
  name='SectionView',
  full_name='services.telemetry.v1beta2.SectionView',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='services.telemetry.v1beta2.SectionView.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='view', full_name='services.telemetry.v1beta2.SectionView.view', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=350,
)


_SECTIONACTION = _descriptor.Descriptor(
  name='SectionAction',
  full_name='services.telemetry.v1beta2.SectionAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='services.telemetry.v1beta2.SectionAction.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='services.telemetry.v1beta2.SectionAction.action', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=447,
)

_SECTIONIMPRESSION.fields_by_name['context'].message_type = analytics_dot_Context__pb2._CONTEXT
_SECTIONIMPRESSION.fields_by_name['impression'].message_type = analytics_dot_commerce_dot_SectionAnalytics__pb2._IMPRESSION
_SECTIONVIEW.fields_by_name['context'].message_type = analytics_dot_Context__pb2._CONTEXT
_SECTIONVIEW.fields_by_name['view'].message_type = analytics_dot_commerce_dot_SectionAnalytics__pb2._VIEW
_SECTIONACTION.fields_by_name['context'].message_type = analytics_dot_Context__pb2._CONTEXT
_SECTIONACTION.fields_by_name['action'].message_type = analytics_dot_commerce_dot_SectionAnalytics__pb2._ACTION
DESCRIPTOR.message_types_by_name['SectionImpression'] = _SECTIONIMPRESSION
DESCRIPTOR.message_types_by_name['SectionView'] = _SECTIONVIEW
DESCRIPTOR.message_types_by_name['SectionAction'] = _SECTIONACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SectionImpression = _reflection.GeneratedProtocolMessageType('SectionImpression', (_message.Message,), dict(
  DESCRIPTOR = _SECTIONIMPRESSION,
  __module__ = 'telemetry.v1beta2.commerce.SectionEvents_Beta2_pb2'
  # @@protoc_insertion_point(class_scope:services.telemetry.v1beta2.SectionImpression)
  ))
_sym_db.RegisterMessage(SectionImpression)

SectionView = _reflection.GeneratedProtocolMessageType('SectionView', (_message.Message,), dict(
  DESCRIPTOR = _SECTIONVIEW,
  __module__ = 'telemetry.v1beta2.commerce.SectionEvents_Beta2_pb2'
  # @@protoc_insertion_point(class_scope:services.telemetry.v1beta2.SectionView)
  ))
_sym_db.RegisterMessage(SectionView)

SectionAction = _reflection.GeneratedProtocolMessageType('SectionAction', (_message.Message,), dict(
  DESCRIPTOR = _SECTIONACTION,
  __module__ = 'telemetry.v1beta2.commerce.SectionEvents_Beta2_pb2'
  # @@protoc_insertion_point(class_scope:services.telemetry.v1beta2.SectionAction)
  ))
_sym_db.RegisterMessage(SectionAction)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n-io.bloombox.schema.services.telemetry.v1beta2H\001P\001\252\002\021Telemetry.v1beta2'))
# @@protoc_insertion_point(module_scope)
