# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytics/commerce/OrderAnalytics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from commerce import Order_pb2 as commerce_dot_Order__pb2
from temporal import Instant_pb2 as temporal_dot_Instant__pb2
from commerce import Customer_pb2 as commerce_dot_Customer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='analytics/commerce/OrderAnalytics.proto',
  package='analytics.order',
  syntax='proto3',
  serialized_pb=_b('\n\'analytics/commerce/OrderAnalytics.proto\x12\x0f\x61nalytics.order\x1a\x14\x63ommerce/Order.proto\x1a\x16temporal/Instant.proto\x1a\x17\x63ommerce/Customer.proto\"\xa6\x01\n\x06\x41\x63tion\x12%\n\torder_key\x18\x01 \x01(\x0b\x32\x12.commerce.OrderKey\x12*\n\x04verb\x18\x02 \x01(\x0e\x32\x1c.analytics.order.OrderAction\x12$\n\x08\x63ustomer\x18\x03 \x01(\x0b\x32\x12.commerce.Customer\x12#\n\x08occurred\x18\x04 \x01(\x0b\x32\x11.temporal.Instant*\xff\x01\n\x0bOrderAction\x12\x0f\n\x0b\x41\x44\x44_TO_CART\x10\x00\x12\x14\n\x10REMOVE_FROM_CART\x10\x01\x12\x10\n\x0cRESTORE_CART\x10\x02\x12\x11\n\rVERIFY_MEMBER\x10\x03\x12\x10\n\x0cORDER_SUBMIT\x10\x04\x12\x10\n\x0cORDER_STATUS\x10\x05\x12\x10\n\x0cORDER_CANCEL\x10\x06\x12\x12\n\x0eORDER_ACCEPTED\x10\x07\x12\x12\n\x0eORDER_REJECTED\x10\x08\x12\x15\n\x11ORDER_IN_PROGERSS\x10\t\x12\x1a\n\x16ORDER_OUT_FOR_DELIVERY\x10\n\x12\x13\n\x0fORDER_FULFILLED\x10\x0b\x42;\n\"io.bloombox.schema.analytics.orderB\x0eOrderAnalyticsH\x01P\x00\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[commerce_dot_Order__pb2.DESCRIPTOR,temporal_dot_Instant__pb2.DESCRIPTOR,commerce_dot_Customer__pb2.DESCRIPTOR,])

_ORDERACTION = _descriptor.EnumDescriptor(
  name='OrderAction',
  full_name='analytics.order.OrderAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD_TO_CART', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVE_FROM_CART', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESTORE_CART', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFY_MEMBER', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_SUBMIT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_CANCEL', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_ACCEPTED', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_REJECTED', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_IN_PROGERSS', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_OUT_FOR_DELIVERY', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_FULFILLED', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=301,
  serialized_end=556,
)
_sym_db.RegisterEnumDescriptor(_ORDERACTION)

OrderAction = enum_type_wrapper.EnumTypeWrapper(_ORDERACTION)
ADD_TO_CART = 0
REMOVE_FROM_CART = 1
RESTORE_CART = 2
VERIFY_MEMBER = 3
ORDER_SUBMIT = 4
ORDER_STATUS = 5
ORDER_CANCEL = 6
ORDER_ACCEPTED = 7
ORDER_REJECTED = 8
ORDER_IN_PROGERSS = 9
ORDER_OUT_FOR_DELIVERY = 10
ORDER_FULFILLED = 11



_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='analytics.order.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_key', full_name='analytics.order.Action.order_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verb', full_name='analytics.order.Action.verb', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customer', full_name='analytics.order.Action.customer', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='occurred', full_name='analytics.order.Action.occurred', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=298,
)

_ACTION.fields_by_name['order_key'].message_type = commerce_dot_Order__pb2._ORDERKEY
_ACTION.fields_by_name['verb'].enum_type = _ORDERACTION
_ACTION.fields_by_name['customer'].message_type = commerce_dot_Customer__pb2._CUSTOMER
_ACTION.fields_by_name['occurred'].message_type = temporal_dot_Instant__pb2._INSTANT
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.enum_types_by_name['OrderAction'] = _ORDERACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
  DESCRIPTOR = _ACTION,
  __module__ = 'analytics.commerce.OrderAnalytics_pb2'
  # @@protoc_insertion_point(class_scope:analytics.order.Action)
  ))
_sym_db.RegisterMessage(Action)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"io.bloombox.schema.analytics.orderB\016OrderAnalyticsH\001P\000\370\001\001'))
# @@protoc_insertion_point(module_scope)
