# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: menu/v1beta1/MenuStream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bq_field_pb2 as bq__field__pb2
import bq_table_pb2 as bq__table__pb2
from identity import UserKey_pb2 as identity_dot_UserKey__pb2
from base import ProductKey_pb2 as base_dot_ProductKey__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='menu/v1beta1/MenuStream.proto',
  package='bloombox.tables.menu.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n\x1dmenu/v1beta1/MenuStream.proto\x12\x1c\x62loombox.tables.menu.v1beta1\x1a\x0e\x62q_field.proto\x1a\x0e\x62q_table.proto\x1a\x16identity/UserKey.proto\x1a\x15\x62\x61se/ProductKey.proto\"\xe2\x07\n\nMenuStream\x12l\n\x04uuid\x18\x01 \x01(\tB^\xf0?\x01\x8a@XEvent UUID. Generated when it happens and used to correlate telemetry with menu changes.\x12\x89\x01\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32(.bloombox.tables.menu.v1beta1.MenuActionBO\xf0?\x01\x8a@ISpecifies the action type that was taken. \'MODIFY\', \'CREATE\' or \'DELETE\'.\x12]\n\x08occurred\x18\x03 \x01(\x04\x42K\xf0?\x01\xfa?\tTIMESTAMP\x8a@9Timestamp describing when this catalog mutation occurred.\x12L\n\x05scope\x18\x04 \x01(\tB=\xf0?\x01\x8a@7Specifies the partnership scope of a given menu change.\x12k\n\x04user\x18\x05 \x01(\x0b\x32!.bloombox.schema.identity.UserKeyB:\xf0?\x01\x8a@4User key that was matched to this checkin operation.\x12\xe0\x01\n\x03key\x18\x06 \x01(\x0b\x32\x1d.opencannabis.base.ProductKeyB\xb3\x01\xf0?\x01\x8a@\xac\x01Product key resulting from a \'CREATE\' operation, deleted during a \'DELETE\' operation, or modified during a \'MODIFY\' operation. Considered the \'subject\' of this transaction.\x12\xd0\x01\n\x07payload\x18\x07 \x01(\tB\xbe\x01\x8a@\xba\x01Raw payload of JSON data describing this product after modifications are applied, if the event is a \'MODIFY\' event, the data saved during a \'CREATE\' event, or empty for a \'DELETE\' event.:\n\xea?\x07\x63\x61talog*0\n\nMenuAction\x12\n\n\x06MODIFY\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x42;\n&io.bloombox.schema.tables.menu.v1beta1B\nMenuTablesH\x01P\x00\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[bq__field__pb2.DESCRIPTOR,bq__table__pb2.DESCRIPTOR,identity_dot_UserKey__pb2.DESCRIPTOR,base_dot_ProductKey__pb2.DESCRIPTOR,])

_MENUACTION = _descriptor.EnumDescriptor(
  name='MenuAction',
  full_name='bloombox.tables.menu.v1beta1.MenuAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODIFY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1139,
  serialized_end=1187,
)
_sym_db.RegisterEnumDescriptor(_MENUACTION)

MenuAction = enum_type_wrapper.EnumTypeWrapper(_MENUACTION)
MODIFY = 0
CREATE = 1
DELETE = 2



_MENUSTREAM = _descriptor.Descriptor(
  name='MenuStream',
  full_name='bloombox.tables.menu.v1beta1.MenuStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='bloombox.tables.menu.v1beta1.MenuStream.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@XEvent UUID. Generated when it happens and used to correlate telemetry with menu changes.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='bloombox.tables.menu.v1beta1.MenuStream.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@ISpecifies the action type that was taken. \'MODIFY\', \'CREATE\' or \'DELETE\'.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='occurred', full_name='bloombox.tables.menu.v1beta1.MenuStream.occurred', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\372?\tTIMESTAMP\212@9Timestamp describing when this catalog mutation occurred.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scope', full_name='bloombox.tables.menu.v1beta1.MenuStream.scope', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@7Specifies the partnership scope of a given menu change.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='bloombox.tables.menu.v1beta1.MenuStream.user', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@4User key that was matched to this checkin operation.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='bloombox.tables.menu.v1beta1.MenuStream.key', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@\254\001Product key resulting from a \'CREATE\' operation, deleted during a \'DELETE\' operation, or modified during a \'MODIFY\' operation. Considered the \'subject\' of this transaction.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='bloombox.tables.menu.v1beta1.MenuStream.payload', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\272\001Raw payload of JSON data describing this product after modifications are applied, if the event is a \'MODIFY\' event, the data saved during a \'CREATE\' event, or empty for a \'DELETE\' event.')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\352?\007catalog')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=1137,
)

_MENUSTREAM.fields_by_name['action'].enum_type = _MENUACTION
_MENUSTREAM.fields_by_name['user'].message_type = identity_dot_UserKey__pb2._USERKEY
_MENUSTREAM.fields_by_name['key'].message_type = base_dot_ProductKey__pb2._PRODUCTKEY
DESCRIPTOR.message_types_by_name['MenuStream'] = _MENUSTREAM
DESCRIPTOR.enum_types_by_name['MenuAction'] = _MENUACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MenuStream = _reflection.GeneratedProtocolMessageType('MenuStream', (_message.Message,), dict(
  DESCRIPTOR = _MENUSTREAM,
  __module__ = 'menu.v1beta1.MenuStream_pb2'
  # @@protoc_insertion_point(class_scope:bloombox.tables.menu.v1beta1.MenuStream)
  ))
_sym_db.RegisterMessage(MenuStream)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n&io.bloombox.schema.tables.menu.v1beta1B\nMenuTablesH\001P\000\370\001\001'))
_MENUSTREAM.fields_by_name['uuid'].has_options = True
_MENUSTREAM.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@XEvent UUID. Generated when it happens and used to correlate telemetry with menu changes.'))
_MENUSTREAM.fields_by_name['action'].has_options = True
_MENUSTREAM.fields_by_name['action']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@ISpecifies the action type that was taken. \'MODIFY\', \'CREATE\' or \'DELETE\'.'))
_MENUSTREAM.fields_by_name['occurred'].has_options = True
_MENUSTREAM.fields_by_name['occurred']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\372?\tTIMESTAMP\212@9Timestamp describing when this catalog mutation occurred.'))
_MENUSTREAM.fields_by_name['scope'].has_options = True
_MENUSTREAM.fields_by_name['scope']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@7Specifies the partnership scope of a given menu change.'))
_MENUSTREAM.fields_by_name['user'].has_options = True
_MENUSTREAM.fields_by_name['user']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@4User key that was matched to this checkin operation.'))
_MENUSTREAM.fields_by_name['key'].has_options = True
_MENUSTREAM.fields_by_name['key']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\360?\001\212@\254\001Product key resulting from a \'CREATE\' operation, deleted during a \'DELETE\' operation, or modified during a \'MODIFY\' operation. Considered the \'subject\' of this transaction.'))
_MENUSTREAM.fields_by_name['payload'].has_options = True
_MENUSTREAM.fields_by_name['payload']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\272\001Raw payload of JSON data describing this product after modifications are applied, if the event is a \'MODIFY\' event, the data saved during a \'CREATE\' event, or empty for a \'DELETE\' event.'))
_MENUSTREAM.has_options = True
_MENUSTREAM._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\352?\007catalog'))
# @@protoc_insertion_point(module_scope)
