# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: media/MediaItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bq_field_pb2 as bq__field__pb2
from media import MediaKey_pb2 as media_dot_MediaKey__pb2
from media import MediaType_pb2 as media_dot_MediaType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='media/MediaItem.proto',
  package='opencannabis.media',
  syntax='proto3',
  serialized_pb=_b('\n\x15media/MediaItem.proto\x12\x12opencannabis.media\x1a\x0e\x62q_field.proto\x1a\x14media/MediaKey.proto\x1a\x15media/MediaType.proto\"\x94\x02\n\tMediaItem\x12W\n\x03key\x18\x01 \x01(\x0b\x32\x1c.opencannabis.media.MediaKeyB,\x8a@)Key uniquely identifying this media item.\x12Q\n\x04type\x18\x02 \x01(\x0b\x32\x1d.opencannabis.media.MediaTypeB$\x8a@!Type of media this is describing.\x12.\n\x04name\x18\x03 \x01(\tB \x8a@\x1d\x46riendly name for this media.\x12+\n\x03uri\x18\x04 \x01(\tB\x1e\x8a@\x1b\x41\x62solute URI to this media.B7\n\x1cio.opencannabis.schema.mediaB\rAttachedMediaH\x01P\x01\xa2\x02\x03OCSb\x06proto3')
  ,
  dependencies=[bq__field__pb2.DESCRIPTOR,media_dot_MediaKey__pb2.DESCRIPTOR,media_dot_MediaType__pb2.DESCRIPTOR,])




_MEDIAITEM = _descriptor.Descriptor(
  name='MediaItem',
  full_name='opencannabis.media.MediaItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='opencannabis.media.MediaItem.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@)Key uniquely identifying this media item.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='opencannabis.media.MediaItem.type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@!Type of media this is describing.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='opencannabis.media.MediaItem.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\035Friendly name for this media.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uri', full_name='opencannabis.media.MediaItem.uri', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\033Absolute URI to this media.')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=383,
)

_MEDIAITEM.fields_by_name['key'].message_type = media_dot_MediaKey__pb2._MEDIAKEY
_MEDIAITEM.fields_by_name['type'].message_type = media_dot_MediaType__pb2._MEDIATYPE
DESCRIPTOR.message_types_by_name['MediaItem'] = _MEDIAITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MediaItem = _reflection.GeneratedProtocolMessageType('MediaItem', (_message.Message,), dict(
  DESCRIPTOR = _MEDIAITEM,
  __module__ = 'media.MediaItem_pb2'
  # @@protoc_insertion_point(class_scope:opencannabis.media.MediaItem)
  ))
_sym_db.RegisterMessage(MediaItem)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034io.opencannabis.schema.mediaB\rAttachedMediaH\001P\001\242\002\003OCS'))
_MEDIAITEM.fields_by_name['key'].has_options = True
_MEDIAITEM.fields_by_name['key']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@)Key uniquely identifying this media item.'))
_MEDIAITEM.fields_by_name['type'].has_options = True
_MEDIAITEM.fields_by_name['type']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@!Type of media this is describing.'))
_MEDIAITEM.fields_by_name['name'].has_options = True
_MEDIAITEM.fields_by_name['name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\035Friendly name for this media.'))
_MEDIAITEM.fields_by_name['uri'].has_options = True
_MEDIAITEM.fields_by_name['uri']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\033Absolute URI to this media.'))
# @@protoc_insertion_point(module_scope)
