# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/IDMedia.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from media import MediaOrientation_pb2 as media_dot_MediaOrientation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity/IDMedia.proto',
  package='bloombox.schema.identity',
  syntax='proto3',
  serialized_pb=_b('\n\x16identity/IDMedia.proto\x12\x18\x62loombox.schema.identity\x1a\x1cmedia/MediaOrientation.proto\"\xb2\x01\n\x11IDMediaAttachment\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.bloombox.schema.identity.IDMedia\x12\x39\n\x0borientation\x18\x02 \x01(\x0e\x32$.opencannabis.media.MediaOrientation\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x12\n\nimage_type\x18\x04 \x01(\r\x12\x0f\n\x07quality\x18\x05 \x01(\x01*>\n\x07IDMedia\x12\x12\n\x0e\x44OCUMENT_FRONT\x10\x00\x12\x11\n\rDOCUMENT_REAR\x10\x01\x12\x0c\n\x08PORTRAIT\x10\x02\x42!\n\x1bio.bloombox.schema.identityH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[media_dot_MediaOrientation__pb2.DESCRIPTOR,])

_IDMEDIA = _descriptor.EnumDescriptor(
  name='IDMedia',
  full_name='bloombox.schema.identity.IDMedia',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOCUMENT_FRONT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOCUMENT_REAR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PORTRAIT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=263,
  serialized_end=325,
)
_sym_db.RegisterEnumDescriptor(_IDMEDIA)

IDMedia = enum_type_wrapper.EnumTypeWrapper(_IDMEDIA)
DOCUMENT_FRONT = 0
DOCUMENT_REAR = 1
PORTRAIT = 2



_IDMEDIAATTACHMENT = _descriptor.Descriptor(
  name='IDMediaAttachment',
  full_name='bloombox.schema.identity.IDMediaAttachment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='bloombox.schema.identity.IDMediaAttachment.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='bloombox.schema.identity.IDMediaAttachment.orientation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='bloombox.schema.identity.IDMediaAttachment.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_type', full_name='bloombox.schema.identity.IDMediaAttachment.image_type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quality', full_name='bloombox.schema.identity.IDMediaAttachment.quality', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=261,
)

_IDMEDIAATTACHMENT.fields_by_name['type'].enum_type = _IDMEDIA
_IDMEDIAATTACHMENT.fields_by_name['orientation'].enum_type = media_dot_MediaOrientation__pb2._MEDIAORIENTATION
DESCRIPTOR.message_types_by_name['IDMediaAttachment'] = _IDMEDIAATTACHMENT
DESCRIPTOR.enum_types_by_name['IDMedia'] = _IDMEDIA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IDMediaAttachment = _reflection.GeneratedProtocolMessageType('IDMediaAttachment', (_message.Message,), dict(
  DESCRIPTOR = _IDMEDIAATTACHMENT,
  __module__ = 'identity.IDMedia_pb2'
  # @@protoc_insertion_point(class_scope:bloombox.schema.identity.IDMediaAttachment)
  ))
_sym_db.RegisterMessage(IDMediaAttachment)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.bloombox.schema.identityH\001P\001'))
# @@protoc_insertion_point(module_scope)
