# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security/access/PartnerPermissions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporal import Instant_pb2 as temporal_dot_Instant__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='security/access/PartnerPermissions.proto',
  package='security.access',
  syntax='proto3',
  serialized_pb=_b('\n(security/access/PartnerPermissions.proto\x12\x0fsecurity.access\x1a\x16temporal/Instant.proto\"\xec\x01\n\rPartnerAccess\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12\x12\n\ngranted_by\x18\x02 \x01(\t\x12%\n\ngranted_at\x18\x03 \x01(\x0b\x32\x11.temporal.Instant\x12\x36\n\nprivileges\x18\x04 \x03(\x0e\x32\".security.access.PartnerPermission\x12\x32\n\tlocations\x18\x05 \x03(\x0b\x32\x1f.security.access.LocationAccess\x12\x15\n\rall_locations\x18\x06 \x01(\x08\x12\r\n\x05\x61\x64min\x18\x64 \x01(\x08\"j\n\x0eLocationAccess\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12\x12\n\ngranted_by\x18\x02 \x01(\t\x12%\n\ngranted_at\x18\x03 \x01(\x0b\x32\x11.temporal.Instant\x12\r\n\x05\x61\x64min\x18\x64 \x01(\x08*T\n\x11PartnerPermission\x12\t\n\x05OWNER\x10\x00\x12\x0e\n\nSUPERVISOR\x10\x01\x12\x0b\n\x07\x42ILLING\x10\x02\x12\t\n\x05\x41UDIT\x10\x03\x12\x0c\n\x08READONLY\x10\x04\x42(\n\"io.bloombox.schema.security.accessH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[temporal_dot_Instant__pb2.DESCRIPTOR,])

_PARTNERPERMISSION = _descriptor.EnumDescriptor(
  name='PartnerPermission',
  full_name='security.access.PartnerPermission',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OWNER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUPERVISOR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BILLING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUDIT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READONLY', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=432,
  serialized_end=516,
)
_sym_db.RegisterEnumDescriptor(_PARTNERPERMISSION)

PartnerPermission = enum_type_wrapper.EnumTypeWrapper(_PARTNERPERMISSION)
OWNER = 0
SUPERVISOR = 1
BILLING = 2
AUDIT = 3
READONLY = 4



_PARTNERACCESS = _descriptor.Descriptor(
  name='PartnerAccess',
  full_name='security.access.PartnerAccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active', full_name='security.access.PartnerAccess.active', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='granted_by', full_name='security.access.PartnerAccess.granted_by', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='granted_at', full_name='security.access.PartnerAccess.granted_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='privileges', full_name='security.access.PartnerAccess.privileges', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locations', full_name='security.access.PartnerAccess.locations', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_locations', full_name='security.access.PartnerAccess.all_locations', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admin', full_name='security.access.PartnerAccess.admin', index=6,
      number=100, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=322,
)


_LOCATIONACCESS = _descriptor.Descriptor(
  name='LocationAccess',
  full_name='security.access.LocationAccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active', full_name='security.access.LocationAccess.active', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='granted_by', full_name='security.access.LocationAccess.granted_by', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='granted_at', full_name='security.access.LocationAccess.granted_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admin', full_name='security.access.LocationAccess.admin', index=3,
      number=100, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=430,
)

_PARTNERACCESS.fields_by_name['granted_at'].message_type = temporal_dot_Instant__pb2._INSTANT
_PARTNERACCESS.fields_by_name['privileges'].enum_type = _PARTNERPERMISSION
_PARTNERACCESS.fields_by_name['locations'].message_type = _LOCATIONACCESS
_LOCATIONACCESS.fields_by_name['granted_at'].message_type = temporal_dot_Instant__pb2._INSTANT
DESCRIPTOR.message_types_by_name['PartnerAccess'] = _PARTNERACCESS
DESCRIPTOR.message_types_by_name['LocationAccess'] = _LOCATIONACCESS
DESCRIPTOR.enum_types_by_name['PartnerPermission'] = _PARTNERPERMISSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PartnerAccess = _reflection.GeneratedProtocolMessageType('PartnerAccess', (_message.Message,), dict(
  DESCRIPTOR = _PARTNERACCESS,
  __module__ = 'security.access.PartnerPermissions_pb2'
  # @@protoc_insertion_point(class_scope:security.access.PartnerAccess)
  ))
_sym_db.RegisterMessage(PartnerAccess)

LocationAccess = _reflection.GeneratedProtocolMessageType('LocationAccess', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONACCESS,
  __module__ = 'security.access.PartnerPermissions_pb2'
  # @@protoc_insertion_point(class_scope:security.access.LocationAccess)
  ))
_sym_db.RegisterMessage(LocationAccess)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"io.bloombox.schema.security.accessH\001P\001'))
# @@protoc_insertion_point(module_scope)
