# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/Instant.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bq_field_pb2 as bq__field__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/Instant.proto',
  package='opencannabis.temporal',
  syntax='proto3',
  serialized_pb=_b('\n\x16temporal/Instant.proto\x12\x15opencannabis.temporal\x1a\x0e\x62q_field.proto\"\x8f\x01\n\x07Instant\x12\x32\n\x07iso8601\x18\x01 \x01(\tB\x1f\x8a@\x1cISO8601-formatted timestamp.H\x00\x12H\n\ttimestamp\x18\x02 \x01(\x04\x42\x33\x8a@0Unix epoch timestamp, at millisecond resolution.H\x00\x42\x06\n\x04specB+\n\x1fio.opencannabis.schema.temporalH\x01P\x01\xa2\x02\x03OCSb\x06proto3')
  ,
  dependencies=[bq__field__pb2.DESCRIPTOR,])




_INSTANT = _descriptor.Descriptor(
  name='Instant',
  full_name='opencannabis.temporal.Instant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iso8601', full_name='opencannabis.temporal.Instant.iso8601', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\034ISO8601-formatted timestamp.')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='opencannabis.temporal.Instant.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@0Unix epoch timestamp, at millisecond resolution.')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='spec', full_name='opencannabis.temporal.Instant.spec',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=66,
  serialized_end=209,
)

_INSTANT.oneofs_by_name['spec'].fields.append(
  _INSTANT.fields_by_name['iso8601'])
_INSTANT.fields_by_name['iso8601'].containing_oneof = _INSTANT.oneofs_by_name['spec']
_INSTANT.oneofs_by_name['spec'].fields.append(
  _INSTANT.fields_by_name['timestamp'])
_INSTANT.fields_by_name['timestamp'].containing_oneof = _INSTANT.oneofs_by_name['spec']
DESCRIPTOR.message_types_by_name['Instant'] = _INSTANT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Instant = _reflection.GeneratedProtocolMessageType('Instant', (_message.Message,), dict(
  DESCRIPTOR = _INSTANT,
  __module__ = 'temporal.Instant_pb2'
  # @@protoc_insertion_point(class_scope:opencannabis.temporal.Instant)
  ))
_sym_db.RegisterMessage(Instant)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037io.opencannabis.schema.temporalH\001P\001\242\002\003OCS'))
_INSTANT.fields_by_name['iso8601'].has_options = True
_INSTANT.fields_by_name['iso8601']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@\034ISO8601-formatted timestamp.'))
_INSTANT.fields_by_name['timestamp'].has_options = True
_INSTANT.fields_by_name['timestamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\212@0Unix epoch timestamp, at millisecond resolution.'))
# @@protoc_insertion_point(module_scope)
