# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bq_field.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bq_field.proto',
  package='gen_bq_schema',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x62q_field.proto\x12\rgen_bq_schema\x1a google/protobuf/descriptor.proto:/\n\x07require\x12\x1d.google.protobuf.FieldOptions\x18\xfe\x07 \x01(\x08:5\n\rtype_override\x12\x1d.google.protobuf.FieldOptions\x18\xff\x07 \x01(\t:.\n\x06ignore\x12\x1d.google.protobuf.FieldOptions\x18\x80\x08 \x01(\x08:3\n\x0b\x64\x65scription\x12\x1d.google.protobuf.FieldOptions\x18\x81\x08 \x01(\tB\x08Z\x06protosb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


REQUIRE_FIELD_NUMBER = 1022
require = _descriptor.FieldDescriptor(
  name='require', full_name='gen_bq_schema.require', index=0,
  number=1022, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)
TYPE_OVERRIDE_FIELD_NUMBER = 1023
type_override = _descriptor.FieldDescriptor(
  name='type_override', full_name='gen_bq_schema.type_override', index=1,
  number=1023, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)
IGNORE_FIELD_NUMBER = 1024
ignore = _descriptor.FieldDescriptor(
  name='ignore', full_name='gen_bq_schema.ignore', index=2,
  number=1024, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)
DESCRIPTION_FIELD_NUMBER = 1025
description = _descriptor.FieldDescriptor(
  name='description', full_name='gen_bq_schema.description', index=3,
  number=1025, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['require'] = require
DESCRIPTOR.extensions_by_name['type_override'] = type_override
DESCRIPTOR.extensions_by_name['ignore'] = ignore
DESCRIPTOR.extensions_by_name['description'] = description
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(require)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(type_override)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(ignore)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(description)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\006protos'))
# @@protoc_insertion_point(module_scope)
