# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/Compression.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base/Compression.proto',
  package='base',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x62\x61se/Compression.proto\x12\x04\x62\x61se\"V\n\x0b\x43ompression\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.base.Compression.Type\"\x10\n\x04Type\x12\x08\n\x04GZIP\x10\x00\x42\x31\n\x17io.bloombox.schema.baseB\x0f\x42\x61seCompressionH\x01P\x01\xf8\x01\x01\x62\x06proto3')
)



_COMPRESSION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='base.Compression.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GZIP', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=102,
  serialized_end=118,
)
_sym_db.RegisterEnumDescriptor(_COMPRESSION_TYPE)


_COMPRESSION = _descriptor.Descriptor(
  name='Compression',
  full_name='base.Compression',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='base.Compression.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='base.Compression.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPRESSION_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=118,
)

_COMPRESSION.fields_by_name['type'].enum_type = _COMPRESSION_TYPE
_COMPRESSION_TYPE.containing_type = _COMPRESSION
DESCRIPTOR.message_types_by_name['Compression'] = _COMPRESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Compression = _reflection.GeneratedProtocolMessageType('Compression', (_message.Message,), dict(
  DESCRIPTOR = _COMPRESSION,
  __module__ = 'base.Compression_pb2'
  # @@protoc_insertion_point(class_scope:base.Compression)
  ))
_sym_db.RegisterMessage(Compression)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027io.bloombox.schema.baseB\017BaseCompressionH\001P\001\370\001\001'))
# @@protoc_insertion_point(module_scope)
