# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: partner/integrations/OnFleetSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='partner/integrations/OnFleetSettings.proto',
  package='bloombox.schema.partner.integrations.onfleet',
  syntax='proto3',
  serialized_pb=_b('\n*partner/integrations/OnFleetSettings.proto\x12,bloombox.schema.partner.integrations.onfleet\"\x1c\n\x1aOnFleetIntegrationFeatures\"m\n\x0fOnFleetSettings\x12Z\n\x08\x66\x65\x61tures\x18\n \x01(\x0b\x32H.bloombox.schema.partner.integrations.onfleet.OnFleetIntegrationFeaturesB;\n/io.bloombox.schema.partner.integrations.onfleetH\x01P\x00\xa2\x02\x03\x42\x42Sb\x06proto3')
)




_ONFLEETINTEGRATIONFEATURES = _descriptor.Descriptor(
  name='OnFleetIntegrationFeatures',
  full_name='bloombox.schema.partner.integrations.onfleet.OnFleetIntegrationFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=120,
)


_ONFLEETSETTINGS = _descriptor.Descriptor(
  name='OnFleetSettings',
  full_name='bloombox.schema.partner.integrations.onfleet.OnFleetSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='bloombox.schema.partner.integrations.onfleet.OnFleetSettings.features', index=0,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=231,
)

_ONFLEETSETTINGS.fields_by_name['features'].message_type = _ONFLEETINTEGRATIONFEATURES
DESCRIPTOR.message_types_by_name['OnFleetIntegrationFeatures'] = _ONFLEETINTEGRATIONFEATURES
DESCRIPTOR.message_types_by_name['OnFleetSettings'] = _ONFLEETSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OnFleetIntegrationFeatures = _reflection.GeneratedProtocolMessageType('OnFleetIntegrationFeatures', (_message.Message,), dict(
  DESCRIPTOR = _ONFLEETINTEGRATIONFEATURES,
  __module__ = 'partner.integrations.OnFleetSettings_pb2'
  # @@protoc_insertion_point(class_scope:bloombox.schema.partner.integrations.onfleet.OnFleetIntegrationFeatures)
  ))
_sym_db.RegisterMessage(OnFleetIntegrationFeatures)

OnFleetSettings = _reflection.GeneratedProtocolMessageType('OnFleetSettings', (_message.Message,), dict(
  DESCRIPTOR = _ONFLEETSETTINGS,
  __module__ = 'partner.integrations.OnFleetSettings_pb2'
  # @@protoc_insertion_point(class_scope:bloombox.schema.partner.integrations.onfleet.OnFleetSettings)
  ))
_sym_db.RegisterMessage(OnFleetSettings)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n/io.bloombox.schema.partner.integrations.onfleetH\001P\000\242\002\003BBS'))
# @@protoc_insertion_point(module_scope)
