# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: partner/integrations/TwilioSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='partner/integrations/TwilioSettings.proto',
  package='bloombox.schema.partner.integrations.twilio',
  syntax='proto3',
  serialized_pb=_b('\n)partner/integrations/TwilioSettings.proto\x12+bloombox.schema.partner.integrations.twilio\"\x1b\n\x19TwilioIntegrationFeatures\"j\n\x0eTwilioSettings\x12X\n\x08\x66\x65\x61tures\x18\n \x01(\x0b\x32\x46.bloombox.schema.partner.integrations.twilio.TwilioIntegrationFeaturesB:\n.io.bloombox.schema.partner.integrations.twilioH\x01P\x00\xa2\x02\x03\x42\x42Sb\x06proto3')
)




_TWILIOINTEGRATIONFEATURES = _descriptor.Descriptor(
  name='TwilioIntegrationFeatures',
  full_name='bloombox.schema.partner.integrations.twilio.TwilioIntegrationFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=117,
)


_TWILIOSETTINGS = _descriptor.Descriptor(
  name='TwilioSettings',
  full_name='bloombox.schema.partner.integrations.twilio.TwilioSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='bloombox.schema.partner.integrations.twilio.TwilioSettings.features', index=0,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=225,
)

_TWILIOSETTINGS.fields_by_name['features'].message_type = _TWILIOINTEGRATIONFEATURES
DESCRIPTOR.message_types_by_name['TwilioIntegrationFeatures'] = _TWILIOINTEGRATIONFEATURES
DESCRIPTOR.message_types_by_name['TwilioSettings'] = _TWILIOSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TwilioIntegrationFeatures = _reflection.GeneratedProtocolMessageType('TwilioIntegrationFeatures', (_message.Message,), dict(
  DESCRIPTOR = _TWILIOINTEGRATIONFEATURES,
  __module__ = 'partner.integrations.TwilioSettings_pb2'
  # @@protoc_insertion_point(class_scope:bloombox.schema.partner.integrations.twilio.TwilioIntegrationFeatures)
  ))
_sym_db.RegisterMessage(TwilioIntegrationFeatures)

TwilioSettings = _reflection.GeneratedProtocolMessageType('TwilioSettings', (_message.Message,), dict(
  DESCRIPTOR = _TWILIOSETTINGS,
  __module__ = 'partner.integrations.TwilioSettings_pb2'
  # @@protoc_insertion_point(class_scope:bloombox.schema.partner.integrations.twilio.TwilioSettings)
  ))
_sym_db.RegisterMessage(TwilioSettings)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n.io.bloombox.schema.partner.integrations.twilioH\001P\000\242\002\003BBS'))
# @@protoc_insertion_point(module_scope)
