# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crypto/primitives/Integrity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crypto/primitives/Integrity.proto',
  package='opencannabis.crypto.primitives.integrity',
  syntax='proto3',
  serialized_pb=_b('\n!crypto/primitives/Integrity.proto\x12(opencannabis.crypto.primitives.integrity\"\x89\x01\n\x04Hash\x12J\n\talgorithm\x18\x01 \x01(\x0e\x32\x37.opencannabis.crypto.primitives.integrity.HashAlgorithm\x12\r\n\x03raw\x18\x02 \x01(\x0cH\x00\x12\r\n\x03hex\x18\x03 \x01(\tH\x00\x12\r\n\x03\x62\x36\x34\x18\x04 \x01(\tH\x00\x42\x08\n\x06\x64igest\"X\n\nHashedData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12<\n\x04hash\x18\x02 \x01(\x0b\x32..opencannabis.crypto.primitives.integrity.Hash*R\n\rHashAlgorithm\x12\x08\n\x04SHA1\x10\x00\x12\x07\n\x03MD5\x10\x01\x12\n\n\x06SHA256\x10\x02\x12\n\n\x06SHA384\x10\x03\x12\n\n\x06SHA512\x10\x04\x12\n\n\x06MURMUR\x10\x06\x42>\n2io.opencannabis.schema.crypto.primitives.integrityH\x01P\x01\xa2\x02\x03OCSb\x06proto3')
)

_HASHALGORITHM = _descriptor.EnumDescriptor(
  name='HashAlgorithm',
  full_name='opencannabis.crypto.primitives.integrity.HashAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHA1', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MD5', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA256', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA384', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA512', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MURMUR', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=309,
  serialized_end=391,
)
_sym_db.RegisterEnumDescriptor(_HASHALGORITHM)

HashAlgorithm = enum_type_wrapper.EnumTypeWrapper(_HASHALGORITHM)
SHA1 = 0
MD5 = 1
SHA256 = 2
SHA384 = 3
SHA512 = 4
MURMUR = 6



_HASH = _descriptor.Descriptor(
  name='Hash',
  full_name='opencannabis.crypto.primitives.integrity.Hash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='opencannabis.crypto.primitives.integrity.Hash.algorithm', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw', full_name='opencannabis.crypto.primitives.integrity.Hash.raw', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hex', full_name='opencannabis.crypto.primitives.integrity.Hash.hex', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b64', full_name='opencannabis.crypto.primitives.integrity.Hash.b64', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='digest', full_name='opencannabis.crypto.primitives.integrity.Hash.digest',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=80,
  serialized_end=217,
)


_HASHEDDATA = _descriptor.Descriptor(
  name='HashedData',
  full_name='opencannabis.crypto.primitives.integrity.HashedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='opencannabis.crypto.primitives.integrity.HashedData.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='opencannabis.crypto.primitives.integrity.HashedData.hash', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=307,
)

_HASH.fields_by_name['algorithm'].enum_type = _HASHALGORITHM
_HASH.oneofs_by_name['digest'].fields.append(
  _HASH.fields_by_name['raw'])
_HASH.fields_by_name['raw'].containing_oneof = _HASH.oneofs_by_name['digest']
_HASH.oneofs_by_name['digest'].fields.append(
  _HASH.fields_by_name['hex'])
_HASH.fields_by_name['hex'].containing_oneof = _HASH.oneofs_by_name['digest']
_HASH.oneofs_by_name['digest'].fields.append(
  _HASH.fields_by_name['b64'])
_HASH.fields_by_name['b64'].containing_oneof = _HASH.oneofs_by_name['digest']
_HASHEDDATA.fields_by_name['hash'].message_type = _HASH
DESCRIPTOR.message_types_by_name['Hash'] = _HASH
DESCRIPTOR.message_types_by_name['HashedData'] = _HASHEDDATA
DESCRIPTOR.enum_types_by_name['HashAlgorithm'] = _HASHALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hash = _reflection.GeneratedProtocolMessageType('Hash', (_message.Message,), dict(
  DESCRIPTOR = _HASH,
  __module__ = 'crypto.primitives.Integrity_pb2'
  # @@protoc_insertion_point(class_scope:opencannabis.crypto.primitives.integrity.Hash)
  ))
_sym_db.RegisterMessage(Hash)

HashedData = _reflection.GeneratedProtocolMessageType('HashedData', (_message.Message,), dict(
  DESCRIPTOR = _HASHEDDATA,
  __module__ = 'crypto.primitives.Integrity_pb2'
  # @@protoc_insertion_point(class_scope:opencannabis.crypto.primitives.integrity.HashedData)
  ))
_sym_db.RegisterMessage(HashedData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n2io.opencannabis.schema.crypto.primitives.integrityH\001P\001\242\002\003OCS'))
# @@protoc_insertion_point(module_scope)
